### PR TITLE
Adds missing PreviewPanel template file to the main reports folder

### PR DESCRIPTION
**Pull request by ssmarco**
See Issue 1841 - BUG Navigating to a page from reports section loads broken CMSMain view

### CODE REVIEW

**Comment by tractorcow** [comment]
It seems a shame that we need to port pages admin functionality to all other sections in order to prevent navigation breaking.

I'll merge this for now, but what I expect should happen is that cross-section navigation prompts a full page reload rather than trying to ajax in Content.

**Comment by tractorcow** [comment]
Oh, I merged this and ported it back to 4 branch, and it didn't fix the issue...

**Comment by tractorcow** [comment]
My bad, I was testing the wrong local checkout. It's fixed. :)

**Comment by ssmarco** [comment]
Yay! :)

**Pull request merged**
